### ISSUE TITLE
Please add support for Youdao workbook

### ISSUE THREAD

**Issue by leira** [youngdze/YoudaoDict#1]
API for Youdao workbook: http://dict.youdao.com/wordbook/ajax?action=addword&q=

**Comment by youngdze** [comment]
@leira 
Considering add this feature in next version. Thanks for your advice.

**Comment by youngdze** [comment]
The support for Youdao wordbook has been added -> https://github.com/youngdze/YoudaoDict/commit/4f479ccb40ff2e92632201ebe08597ec11b0b2e9
