### ISSUE TITLE
一直在加载中，不出现查询结果

### ISSUE THREAD

**Issue by taolin2107** [youngdze/YoudaoDict#11]
1. 有时候出现一直在加载中，不能显示结果。
2. 搜索历史不能隐藏，挡住了搜索框。

![wx20161230-110546](https://cloud.githubusercontent.com/assets/2200131/21559059/f0ead09a-ce7f-11e6-844e-54b84e24325d.png)

**Comment by youngdze** [comment]
Fixed in v0.3.5
