### ISSUE TITLE
点击more>>跳转到有道词典页面时没有带上查询的词条

### ISSUE THREAD

**Issue by taolin2107** [youngdze/YoudaoDict#13]
如下图，点击more>>，对应的链接是http://dict.youdao.com/search?q=#{word}, 为什么不是 http://dict.youdao.com/search?q=Interface

![image](https://cloud.githubusercontent.com/assets/2200131/23110573/5413d1ac-f75d-11e6-9572-8245641df9a2.png)

**Comment by youngdze** [comment]
fixed in v0.3.6
