### ISSUE TITLE
偶尔出现"query failed"的情况

### ISSUE THREAD

**Issue by subcrew** [youngdze/YoudaoDict#15]
chrome英译汉, 应该不是代理的问题,  重启chrome也不管用

**Comment by youngdze** [comment]
请问有没有设置了私人 Key，公用 Key 有一小时内次数限制的，由于使用的人数过多，建议使用私人Key。

打开设置 -> 使用我的 Key -> 填写 Key

**Comment by subcrew** [comment]
@youngdze thx!
