### ISSUE TITLE
The "Referer" item  in Request Headers will leak user's privacy.

### ISSUE THREAD

**Issue by zoumi** [youngdze/YoudaoDict#3]
It may be not easy to solve this problem.But I think you should show the Warning to your users, expecially when they have logined *.youdao.com.

**Comment by youngdze** [comment]
I have removed "Referrer" from Request Headers. You can check  https://github.com/youngdze/YoudaoDict/commit/30c51e4f068fb82815ea8c650f60ffa8116fef36 out.
