### ISSUE TITLE
 Future Request: Add the shortcut for popping up the query interface

### ISSUE THREAD

**Issue by louchenyao** [youngdze/YoudaoDict#7]
Sometimes I need query some words which cannot be selected by mouse (the words in the picture), and I need to query word which not in the browser.
This feature is very useful for me, I hope you can consider to add it into roadmap.

**Comment by youngdze** [comment]
Figuring out words in the picture is very difficult for such a Chrome extension.  My programming skill is too poor to accomplish the feature, it's not on the product roadmap either.
You can try other alternative tools which can figure out words in the pictures or other places.
If you can give a hand to the feature, feel free to send PR.

**Comment by youngdze** [comment]
I recently found Chrome had supported user to config keyboard shortcuts for specified extension.

This feature will be included in next version.

**Comment by youngdze** [comment]
Fixed in v0.3.5
